# Generated by Django 3.0.5 on 2020-04-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GymAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='gymcenters/')),
                ('location', models.TextField()),
                ('Mobile', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('experience', models.IntegerField()),
                ('Subscription', models.IntegerField()),
                ('Per_time', models.TextField(choices=[('day', 'Daily'), ('week', 'Weekly'), ('month', 'Monthly'), ('quarter', 'Quarterly'), ('year', 'Yearly')])),
                ('service', models.TextField(help_text='enter various services you offer separated by comma (,)')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='trainers/')),
                ('age', models.IntegerField()),
                ('Mobile', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Experience', models.IntegerField(help_text='enter years of gym or coaching experience')),
                ('Specialty', models.TextField(choices=[('Yoga', 'Yoga'), ('Body Building', 'Body Building'), ('Dieting', 'Dieting')])),
                ('Per_time', models.TextField(choices=[('day', 'Daily'), ('week', 'Weekly'), ('month', 'Monthly'), ('quarter', 'Quarterly'), ('year', 'Yearly')])),
                ('service', models.TextField(help_text='enter various services you offer separated by comma (,)')),
                ('Pricing', models.IntegerField(help_text='how much do you charge by duration')),
            ],
        ),
    ]
