# Generated by Django 3.0.5 on 2020-04-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymagency',
            name='Per_time',
            field=models.TextField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')]),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='Per_time',
            field=models.TextField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')]),
        ),
    ]
